# Site settings
title: Magnaball
email: 
description: > # this means to ignore newlines until "baseurl:"
  Trying to get a Magnaball ticket. I sold my Glen Close on Cash or Trade last week. Went to Mann2.
  Then was going to buy my GA Saturday to camp with friends, sold out. So know curious how many other phans need tix. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nygeog.com" # the base hostname & protocol for your site
twitter_username: nygeog
github_username:  nygeog

# Build settings
markdown: kramdown
